config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: "/sidekiq"
  
  namespace :admin do
    resources :posts
    resources :likes
    resources :users
    resources :contacts

    root to: 'posts#index'
  end

  resources :infos, only: %i[index create]

  resources :likes, only: :index

  resources :rooms, only: %i[create index show]
  resources :messages, only: [:create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'appearance', to: 'dashboard#appearance'
  
  root 'dashboard#index'
  get 'dashboard', to: 'dashboard#index'
  get ':id', to: 'dashboard#show', as: :user

  resources :posts do
    resource :likes

    member do
      get 'update_updated_at', to: 'dashboard#update'
    end
  end

  resources :tags, only: [:show]
  resources :contacts, only: %i[new create]

end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :set_user, only: %i[show]
  before_action :set_post, only: %i[update]

  def index
    info = Info.last
    flash[:notice] = info.title if info&.respond_to?(:created_today?) && info.created_today?

    @q = Post.order(updated_at: :desc).ransack(params[:q])
    @posts = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def appearance
  end

  def show
    # アクションメーラー
    @contact = Contact.new

    # DM
    redirect_to dashboard_path if @user.nil?

    return unless current_user
    @current_entry = current_user.entries
    @another_entry = @user.entries
    
    return if @user.id == current_user.id
    result = Room.check_room_ids(@current_entry, @another_entry)
    @is_room = result[:is_room]
    @room_id = result[:room_id] if result[:is_room]
    
    return if @is_room
    @room = Room.new
    @entry = Entry.new
  end

  def update
    return unless current_user
    @post.touch
    redirect_to dashboard_path, notice: '投稿日時を更新しました。'
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/views/dashboard/appearance.html.erb
<main class="profile l-inner">
    <h1 style="text-align:center;"><%= local_user_name %> アカウント編集</h1>
    
    <%= simple_form_for(current_user,
        url: registration_path(current_user), 
        html: { method: :put }, 
        data: { turbo: false }) do |f| %>
        
        <div class="">
            <%= image_tag(current_user.avatar, class:"avatar-image") if current_user.avatar.attached? %>
        </div>
        <div class="">
            <%= f.input :avatar, required: false, label: false %>
        </div>
        
        <div class="">
            <%= local_user_column_name(:username) %>
            <%= f.input :full_name, placeholder: "Your full name...", label: false, class:"form-control", required: false %>
        </div>
        <div class="">
            Twitterの@以降
            <%= f.input :username, placeholder: "Your username...", label: false, class:"form-control", required: true %>
        </div>
        <div class="">
            説明
            <%= f.input :body, placeholder: "About you...", label: false, class:"form-control", required: false %>
        </div>
        
        <div class="">
            <%= f.submit "アカウント更新", class: "btn btn-primary" %>
        </div>
        
    <% end %>
</main>

app/views/dashboard/index.html.erb
<div class="search__nav">
  <div class="search__form">
    <%= render 'shared/search_form' %>
  </div>
</div>

<main class="top">
    <div class="l-inner">

        <div class="top__mainContents">
            <div>
                <%= image_tag "title.png", alt: "", class: "title" %>
            </div>
            <div class="top__contents">
                <table>
                    <tbody>
                        <% @posts.each do |post| %>
                            <tr>
                                <td>
                                    <%= link_to user_path(post.user.id) do %>
                                        <% if post.user.avatar.attached? %>
                                            <%= image_tag(post.user.avatar, class:"avatar") %>
                                        <% else %>
                                            <%= image_tag "account.png", alt: "ロゴ", class: "avatar" %>
                                        <% end %>
                                    <% end %>
                                </td>
                                <!-- <td><%= link_to post.user.username, user_path(post.user.id), class: "" %></td> -->
                                <td>
                                    <div class="flex">
                                        <%= format_date post.updated_at %> 
                                        <%= link_to truncate_text(post.title, 10), post, class: "td-title" %>
                                        <i class="far fa-folder icon--adjustment"></i>
                                        <% if post.category %>
                                            <span class="category"><%= post.category.name %><span>
                                        <% end %>
                                    </div>
                                    <div>
                                        <%= link_to truncate_text(post.body, 60), post, class: "pc-display" %>
                                        <%= link_to truncate_text(post.body, 18), post, class: "sp-display" %>
                                        <div class="flex">
                                            <% if post.hashtags %>
                                                <span class="tag"><%= post.hashtags %></span>
                                            <% end %>
                                        </div>
                                    </div>
                                </td>
                                <!--<td><%= format_date post.created_at %></td>-->
                                <% if current_user %>
                                <td>
                                    <% if current_user.likes.exists?(post_id: post.id) %>
                                        <i class="fas fa-heart"></i>
                                    <% else %>
                                        <%= link_to post_likes_path(post), method: :post do %>
                                            <i class="far fa-heart"></i>
                                        <% end %>
                                    <% end %>
                                </td>
                                <% end %>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>

            <%= paginate @posts %>
            
        </div><!--top__left-->

        <div class="top__sidebar">
            <a href="https://audiostock.jp/artists/52178" target="_blank" ><img src="https://audiostock.jp/assets/as_banner/banner_300_250_04.png" class="bnr" alt="AudiostockでBGM・効果音を販売中！" ></a>

            <br>
            <%= link_to "https://bit.ly/3MsLijJ" do %>
                <%= image_tag "bnr2.png", alt: "", class: "bnr" %>
            <% end %>
            
            <br>
            <%= link_to "https://kurataaudio.store/" do %>
                <%= image_tag "sale-bnr.png", alt: "", class: "bnr" %>
            <% end %>

            <br>
            <%= link_to "https://kurataaudio.net/" do %>
                <%= image_tag "production-bnr.png", alt: "", class: "bnr" %>
            <% end %>
            
            
        </div><!--top__right-->

    </div><!--l-inner-->
</main>

app/views/dashboard/show.html.erb
<% breadcrumb :posts %>

<main class="profile">
    <div class="l-inner">
        <div class="profile__contents">

            <div class="profile__info">
                <% if @user.avatar.attached? %>
                    <%= image_tag(@user.avatar, class:"avatar__icon") %>
                <% else %>
                    <%= image_tag "account.png", alt: "ロゴ", class: "avatar__icon" %>
                <% end %>
            
                <h1><%= truncate_text(@user.username, 80) if @user.username %> さんの投稿</h1>
            </div>
            <br>
            
            <div class="profile__content"><p><%= truncate_text(@user.body, 80) if @user.body %></p></div>
            <div class="profile__content flex">
                
                <!-- DM -->
                <% if current_user %>
                    <div class="profile__contentItem">
                        <% unless @user.id == current_user.id %>
                            <% if @is_room == true %>
                            <!-- 新規 -->
                                <%= link_to 'DM', room_path(@room_id) %>
                            <% else %>
                            <!-- 過去 -->
                                <%= form_for @room do |f| %>
                                    <%= fields_for @entry do |e| %>
                                        <%= e.hidden_field :user_id, value: @user.id %>
                                    <% end %>
                                <%= f.button "DM", type: :submit, class: "btn btn-primary" %>
                                <% end %>
                            <% end %>
                        <% end %>
                    </div>
                <% end %>
            </div>
            
            <table>
                <tbody>
                    <% @user.posts.order(updated_at: :desc).each do |post| %>
                    <tr>
                        <td><%= format_date post.updated_at %></td>
                        <td>
                            <%= link_to truncate_text(post.title, 80), post, class: "" if post.title %>
                            
                            <i class="far fa-folder icon--adjustment"></i>
                            <% if post.category %>
                                <span class="category"><%= post.category.name %><span>
                            <% end %>
                        </td>
                        
                        <% if current_user %>
                            <% if @user.id == current_user.id %>
                            <td><%= link_to '投稿日時を更新', update_updated_at_post_path(post), class: "btn btn-primary" %></td>
                            <td><%= link_to '記事を編集', edit_post_path(post), class: "btn btn-primary" %></td>
                            <% end %>
                        <% end %>
                        
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <br>

            <% if current_user %>
                <button id="toggleAccordion" class="btn btn-danger">メール</button>
                <div class="profile__content accordion">
                    <%= form_with(model: @contact, url: contacts_path, local: true) do |form| %>

                        <%= form.hidden_field :name, value: @user.full_name, class: "form-control" %>

                        <br>
                        <%= form.label :message %>
                        <%= form.text_area :message, class: "form-control" %>

                        <%= form.submit "送信", class: "btn btn-primary" %>
                    <% end %>
                </div>
            <% end %>
        
        </div>

        <div class="profile__sidebar">
            <a href="https://audiostock.jp/artists/52178" target="_blank" ><img src="https://audiostock.jp/assets/as_banner/banner_300_250_04.png" class="bnr" alt="AudiostockでBGM・効果音を販売中！" ></a>

            <br>
            <%= link_to "https://bit.ly/3MsLijJ" do %>
                <%= image_tag "bnr2.png", alt: "", class: "bnr" %>
            <% end %>
            
            <br>
            <%= link_to "https://kurataaudio.store/" do %>
                <%= image_tag "sale-bnr.png", alt: "", class: "bnr" %>
            <% end %>

            <br>
            <%= link_to "https://kurataaudio.net/" do %>
                <%= image_tag "production-bnr.png", alt: "", class: "bnr" %>
            <% end %>
            
            
        </div><!--profile__sidebar-->

    </div>
</main>