config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: "/sidekiq"
  
  namespace :admin do
    resources :posts
    resources :likes
    resources :users
    resources :contacts

    root to: 'posts#index'
  end

  resources :infos, only: %i[index create]

  resources :likes, only: :index

  resources :rooms, only: %i[create index show]
  resources :messages, only: [:create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'appearance', to: 'dashboard#appearance'
  
  root 'dashboard#index'
  get 'dashboard', to: 'dashboard#index'
  get ':id', to: 'dashboard#show', as: :user

  resources :posts do
    resource :likes

    member do
      get 'update_updated_at', to: 'dashboard#update'
    end
  end

  resources :tags, only: [:show]
  resources :contacts, only: %i[new create]

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts

  def self.options
    Category.all.collect { |val| [val.name, val.id] }
  end

  def self.search_options
    Category.all.collect { |val| [val.name, val.name] }
  end

  # NOTE: ransack
  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at id name updated_at]
  end
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/info.rb
# frozen_string_literal: true

class Info < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Info.create!(
        title: row['title'],
        body: row['body']
      )
    end
  end

  def created_today?
    created_at.to_date == Date.today
  end
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :tag, optional: true
  belongs_to :category, optional: true
  has_many :post_tags
  has_many :tags, through: :post_tags

  before_validation :format_hashtags

  validates :title, presence: true
  validates :body, presence: true

  # NOTE: ransack
  def self.ransackable_attributes(_auth_object = nil)
    %w[title body hashtags created_at]
  end

  # NOTE: ransack
  def self.ransackable_associations(_auth_object = nil)
    %w[category post_tags hashtags tags user]
  end

  def format_hashtags
    self.hashtags = hashtags.split(' ').map { |hashtag| hashtag.length > 1 ? "##{hashtag}" : "##{hashtag}" }.join(' ')
  end
end

app/models/post_tag.rb
# frozen_string_literal: true

class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy


  # 2つの配列から同じroom_idを持つオブジェクトがあるかどうかを確認しハッシュで返す
  # @param current_entries [Array] 比較対象の配列1
  # @param another_entries [Array] 比較対象の配列2
  # @return [Hash] is_roomとroom_idをキーとする値を持つハッシュ
  def self.check_room_ids(current_entries, another_entries)
    is_room = false
    room_id = nil

    current_entries.each do |current|
      another_entries.each do |another|
        next unless current.room_id == another.room_id

        is_room = true
        room_id = current.room_id
        break
      end

      break if is_room
    end

    { is_room: is_room, room_id: room_id }
  end
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_one_attached :avatar

  validates :full_name, length: { maximum: 50 }
  validates :body, length: { maximum: 80 }
  validate :valid_username

  
  def valid_username
    restricted_username_list = %(admin root dashboard analytics appearance settings preferences calendar)
    errors.add(:username, 'is restricted') if restricted_username_list.include?(username)
  end
end

app/controllers/infos_controller.rb
# frozen_string_literal: true

require 'csv'

class InfosController < ApplicationController
  before_action :authenticate, only: %i[index create]

  def index
  end

  def create
    file = params[:file]
    if file.present? && file.content_type == 'text/csv'
      Info.import(file)
      redirect_to dashboard_path, notice: 'インポート成功'
    else
      redirect_to dashboard_path, notice: 'インポート失敗'
    end
  end

  private

  def authenticate_user(username, password)
    username == ENV['ACCOUNT'] && password == ENV['PASSWORD']
  end

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      authenticate_user(username, password)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def format_date(date)
    current_time = Time.zone.now
    one_month_in_seconds = 10 * 24 * 60 * 60

    if current_time - date >= one_month_in_seconds
      date.strftime('%Y年%m月%d日')
    else
      "#{distance_of_time_in_words_to_now(date)}前"
    end
  end

  def truncate_text(text, limit)
    if text.length > limit
      truncated_text = text[0...limit]
      truncated_text += '...'
      sanitize truncated_text, tags: %w[strong em], attributes: []
    else
      sanitize text, tags: %w[strong em], attributes: []
    end
  end

  # NOTE: ローカライズ
  def local_user_name
    User.model_name.human
  end

  # NOTE: ローカライズ
  def local_user_column_name(column)
    User.human_attribute_name(column)
  end

  # NOTE: schema
  def default_meta_tags
    {
      site: 'my.band',
      title: 'my.band',
      reverse: true,
      separator: '|',
      description: 'バンドメンバー募集掲示板',
      keywords: 'my.band, バンドメンバー, 募集, 掲示板',
      canonical: request.original_url,
      noindex: !Rails.env.production?,
      og: {
        site_name: 'my.band',
        title: 'my.band',
        description: 'バンドメンバー募集掲示板',
        type: 'website',
        url: request.original_url,
        locale: 'ja_JP'
      },
      twitter: {
        card: 'summary_large_image',
        site: '@BeatsaberDJP'
      }
    }
  end

  # NOTE: schema
  def schema
    description = 'バンドメンバー募集掲示板'

    {
      "@context": 'https://schema.org',
      "@type": 'DiscussionForumPosting',
      "headline": description.to_s
    }
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/infos_helper.rb
# frozen_string_literal: true

module InfosHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag('favicon.ico') %>
    <%= display_meta_tags default_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel ="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    
    <%= javascript_importmap_tags %>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-PHL3VLH4C5"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-PHL3VLH4C5');
    </script>
    
  </head>

  <body>
    <%= render partial: "shared/alerts" %>
    <%= render partial: "shared/navbar" unless devise_controller?  %>

    <%= yield %>

    <div class="breadcrumbs">
      <%= breadcrumbs separator: " &rsaquo; " %>
    </div>
    
    <footer class="footer">
      <%= link_to "copyright© My.Band", root_path, class: "" %>
    </footer>

    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script src="/js/common.js"></script>
    <% params %>

    <script type="application/ld+json">
    <%= schema %>
    </script>
  </body>
</html>

app/views/shared/_alerts.html.erb
<% if flash[:notice] %>
<p class="alert alert-success"><%= notice %></p>
<% elsif flash[:alert] %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header class="header">
    <div class="header__inner">
        <div class="header__logo">
            <%= link_to root_path do %>
              <%= image_tag "logo.png", alt: "ロゴ", class: "logo" %>
            <% end %>
        </div>
        <div class="header__left">
            <ul class="header__headNav headNav">
              <% if user_signed_in? %>
                <li class="headNav__item"><%= link_to "新しい投稿", new_post_path, class: "" %></li>
                <li class="headNav__item"><%= link_to "マイアカウント", edit_user_registration_path, class: "" %></li>
                <li class="headNav__item"><%= link_to "外観", appearance_path, class: "" %></li>
                <li class="headNav__item"><%= link_to "チャット一覧", rooms_path, class: "" %></li>
                <li class="headNav__item"><%= link_to "いいね一覧", likes_path, class: "" %></li>
                <li class="headNav__item"><%= link_to "ログアウト", destroy_user_session_path, :method => :delete, class: "btn btn-danger logout" %></li>
              <% else %>
                <li class="headNav__item"><%= link_to "ログイン", new_user_session_path, class: "btn btn-primary login" %></li>
              <% end %>
            </ul>
        </div>
        <button class="header__ham ham" id="js-ham">
            <span></span>
            <span></span>
            <span></span>
        </button>
    </div>
    <nav class="header__nav nav" id="js-nav">
        <ul class="nav__items navItems">
          <% if user_signed_in? %>
            <li class="headNav__item"><%= link_to "新しい投稿", new_post_path, class: "" %></li>
            <li class="headNav__item"><%= link_to "マイアカウント", edit_user_registration_path, class: "" %></li>
            <li class="headNav__item"><%= link_to "外観", appearance_path, class: "" %></li>
            <li class="headNav__item"><%= link_to "チャット一覧", rooms_path, class: "" %></li>
            <li class="headNav__item"><%= link_to "いいね一覧", likes_path, class: "" %></li>
            <li class="headNav__item"><%= link_to "ログアウト", destroy_user_session_path, :method => :delete, class: "" %></li>
          <% else %>
            <li class="headNav__item"><%= link_to "ログイン", new_user_session_path, class: "" %></li>
          <% end %>
        </ul>
    </nav>
</header>

app/views/shared/_search_form.html.erb
<%= search_form_for @q, url: dashboard_path do |f| %>
   <div class="search">
      
      <div class="search__left">
            <%= f.search_field :title_or_body_or_hashtags_cont, class: 'search__field', placeholder: '検索ワード' %>
            <br class="sp-display">
            <%= f.select :category_name_cont, options_for_select([["選択してください", ""]] + Category.search_options) %>
      </div>

      <div class="search__right">
         <% sort_link(@q, :created_at, "日付順", class:'search__link') %>
         <%= f.submit '検索', class: 'search__link' %>
      </div>
      
   </div>
<% end %>