config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, at: "/sidekiq"
  
  namespace :admin do
    resources :posts
    resources :likes
    resources :users
    resources :contacts

    root to: 'posts#index'
  end

  resources :infos, only: %i[index create]

  resources :likes, only: :index

  resources :rooms, only: %i[create index show]
  resources :messages, only: [:create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'appearance', to: 'dashboard#appearance'
  
  root 'dashboard#index'
  get 'dashboard', to: 'dashboard#index'
  get ':id', to: 'dashboard#show', as: :user

  resources :posts do
    resource :likes

    member do
      get 'update_updated_at', to: 'dashboard#update'
    end
  end

  resources :tags, only: [:show]
  resources :contacts, only: %i[new create]

end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :tag, optional: true
  belongs_to :category, optional: true
  has_many :post_tags
  has_many :tags, through: :post_tags

  before_validation :format_hashtags

  validates :title, presence: true
  validates :body, presence: true

  # NOTE: ransack
  def self.ransackable_attributes(_auth_object = nil)
    %w[title body hashtags created_at]
  end

  # NOTE: ransack
  def self.ransackable_associations(_auth_object = nil)
    %w[category post_tags hashtags tags user]
  end

  def format_hashtags
    self.hashtags = hashtags.split(' ').map { |hashtag| hashtag.length > 1 ? "##{hashtag}" : "##{hashtag}" }.join(' ')
  end
end

app/controllers/admin/posts_controller.rb
# frozen_string_literal: true

module Admin
  class PostsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to dashboard_path, notice: '投稿しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to dashboard_path, notice: '更新しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def show
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :hashtags, :category_id, tag_ids: [])
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<main class="l-inner session-manager-container">
  <h1 class="session-manager-header">投稿を編集</h1>

  <%= form_for(@post, url: post_path(@post), method: :patch) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div>
      <%= f.label :title %><br>
      <%= f.text_field :title, autofocus: true, class: "form-control" %>
    </div>
    
    <div>
      <%= f.label :category %>
      <%= f.select :category_id, Category.options, prompt: '選択してください' %>
    </div>
    <br>
    
    <div>
      <%= f.label :body %><br>
      <%= f.text_area :body, class: "form-control", style:"height: 300px;" %>
    </div>

    <div>
        <%= f.label :hashtags, 'タグ', style: 'display: block' %>
        <%= f.text_area :hashtags, rows: 4 %>
    </div>
    <br>
    
    <div>
      <%= f.submit "更新する" %>
    </div>
    <br>
    <br>
  <% end %>
</main>

app/views/posts/new.html.erb
<main class="l-inner session-manager-container">
  <h1 class="session-manager-header">新しい投稿</h1>

    <%= form_for(@post, url: posts_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div>
            <%= f.label :title %><br>
            <%= f.text_field :title, autofocus: true, class: "form-control" %>
        </div>
        
        <div>
            <%= f.label :category %>
            <%= f.select :category_id, Category.options, prompt: '選択してください' %>
        </div>
        <br>
        
        <div>
            <%= f.label :body %><br>
            <%= f.text_area :body, class: "form-control", style:"height: 300px;" %>
        </div>

        <div>
            <%= f.label :hashtags, 'タグ', style: 'display: block' %>
            <%= f.text_area :hashtags, rows: 2, class: "form-control" %>
        </div>
        <br>
        
        <div>
            <%= f.submit "投稿する", class: "btn btn-primary" %>
        </div>
        <br>
        <br>

    <% end %>

</main>

app/views/posts/show.html.erb
<main class="posts">
  <div class="l-inner">

    <div class="posts__contents">
      <h1><%= @post.title %></h1>
      
      <div class="posts__info">
        <%= link_to user_path(@post.user.id) do %>
          <% if @post.user.avatar.attached? %>
              <%= image_tag(@post.user.avatar, class:"avatar__icon") %>
          <% else %>
              <%= image_tag "account.png", alt: "ロゴ", class: "avatar__icon" %>
          <% end %>          
        <% end %>
        
        <h2><%= truncate_text(@post.user.username, 80) if @post.user.username %> さん</h2>
      </div>

      <br>
      <p><%= sanitize @post.body, tags: %w(br a), attributes: %w(href) %></p>

    </div>

    <div class="posts__sidebar">
        <a href="https://audiostock.jp/artists/52178" target="_blank" ><img src="https://audiostock.jp/assets/as_banner/banner_300_250_04.png" class="bnr" alt="AudiostockでBGM・効果音を販売中！" ></a>

        <br>
        <%= link_to "https://bit.ly/3MsLijJ" do %>
            <%= image_tag "bnr2.png", alt: "", class: "bnr" %>
        <% end %>
        
        <br>
        <%= link_to "https://kurataaudio.store/" do %>
            <%= image_tag "sale-bnr.png", alt: "", class: "bnr" %>
        <% end %>

        <br>
        <%= link_to "https://kurataaudio.net/" do %>
            <%= image_tag "production-bnr.png", alt: "", class: "bnr" %>
        <% end %>
        
        
    </div><!--posts__sidebar-->

  </div>
</main>